class Collision {


    /**
     * The Collider we hit (Read Only).
     */
    get collider() {}

    /**
     * The Collider we hit (Read Only).
     */
    set collider(value) {}

    /**
     * The contact points generated by the physics engine.
     */
    get contacts() {}

    /**
     * The contact points generated by the physics engine.
     */
    set contacts(value) {}

    /**
     * The GameObject whose collider we are colliding with. (Read Only).
     */
    get gameObject() {}

    /**
     * The GameObject whose collider we are colliding with. (Read Only).
     */
    set gameObject(value) {}

    /**
     * The total impulse applied to this contact pair to resolve the collision.
     */
    get impulse() {}

    /**
     * The total impulse applied to this contact pair to resolve the collision.
     */
    set impulse(value) {}

    /**
     * The relative linear velocity of the two colliding objects (Read Only).
     */
    get relativeVelocity() {}

    /**
     * The relative linear velocity of the two colliding objects (Read Only).
     */
    set relativeVelocity(value) {}

    /**
     * The Rigidbody we hit (Read Only). This is null if the object we hit is a collider with no rigidbody attached.
     */
    get rigidbody() {}

    /**
     * The Rigidbody we hit (Read Only). This is null if the object we hit is a collider with no rigidbody attached.
     */
    set rigidbody(value) {}

    /**
     * The Transform of the object we hit (Read Only).
     */
    get transform() {}

    /**
     * The Transform of the object we hit (Read Only).
     */
    set transform(value) {}


}