class ObjectNames {

    /**
     * Class name of an object.
     */
    static GetClassName() {}

    /**
     * Drag and drop title for an object.
     */
    static GetDragAndDropTitle() {}

    /**
     * Inspector title for an object.
     */
    static GetInspectorTitle() {}

    /**
     * Make a unique name using the provided name as a base. If the target name is in the provided list of existing names, a unique name is generated by appending the next available numerical increment.
     */
    static GetUniqueName() {}

    /**
     * Make a displayable name for a variable.
     */
    static NicifyVariableName() {}

    /**
     * Sets the name of an Object.
     */
    static SetNameSmart() {}



}